import { randomBytes, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";

type ScryptCallback = (
  password: string,
  salt: Buffer,
  keyLength: number,
  options: { N: number; r: number; p: number; maxmem: number },
  callback: (error: Error | null, derivedKey: Buffer) => void
) => void;

const SALT_BYTES = 16;
const KEY_LENGTH = 32;
const SCRYPT_N = 16_384;
const SCRYPT_R = 8;
const SCRYPT_P = 1;
const HASH_PREFIX = `scrypt$${SCRYPT_N}$${SCRYPT_R}$${SCRYPT_P}$${KEY_LENGTH}`;
const MAX_SCRYPT_N = SCRYPT_N;
const MAX_SCRYPT_R = SCRYPT_R;
const MAX_SCRYPT_P = SCRYPT_P;
const MAX_SCRYPT_MEMORY = 32 * 1024 * 1024;
const MAX_SALT_BYTES = 64;

function deriveScryptKey(
  secret: string,
  salt: Buffer,
  keyLength: number,
  options: { N: number; r: number; p: number; maxmem: number }
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const scrypt = scryptCallback as unknown as ScryptCallback;
    scrypt(secret, salt, keyLength, options, (error, derivedKey) => {
      if (error) reject(error);
      else resolve(derivedKey);
    });
  });
}

/**
 * Produces a self-describing, salted scrypt hash for a user-provided secret.
 * The original secret is never returned or persisted.
 */
export async function hashSecret(secret: string): Promise<string> {
  const salt = randomBytes(SALT_BYTES);
  const derivedKey = await deriveScryptKey(secret, salt, KEY_LENGTH, {
    N: SCRYPT_N,
    r: SCRYPT_R,
    p: SCRYPT_P,
    maxmem: MAX_SCRYPT_MEMORY
  });
  return `${HASH_PREFIX}$${salt.toString("base64url")}$${derivedKey.toString("base64url")}`;
}

/** Verifies a secret against a hash generated by {@link hashSecret}. */
export async function verifySecret(secret: string, encodedHash: string): Promise<boolean> {
  const [algorithm, nValue, rValue, pValue, keyLengthValue, saltValue, hashValue] = encodedHash.split("$");
  const n = Number(nValue);
  const r = Number(rValue);
  const p = Number(pValue);
  const keyLength = Number(keyLengthValue);

  if (
    algorithm !== "scrypt" ||
    !Number.isSafeInteger(n) ||
    !Number.isSafeInteger(r) ||
    !Number.isSafeInteger(p) ||
    !Number.isSafeInteger(keyLength) ||
    n < 2 ||
    r < 1 ||
    p < 1 ||
    n > MAX_SCRYPT_N ||
    r > MAX_SCRYPT_R ||
    p > MAX_SCRYPT_P ||
    // Node's scrypt requires N to be a power of two. Validate it before
    // allocating so malformed persisted data cannot consume excessive CPU.
    (n & (n - 1)) !== 0 ||
    keyLength < 16 ||
    keyLength > 128 ||
    !saltValue ||
    !hashValue
  ) {
    return false;
  }

  try {
    const salt = Buffer.from(saltValue, "base64url");
    const expected = Buffer.from(hashValue, "base64url");
    if (!salt.length || salt.length > MAX_SALT_BYTES || expected.length !== keyLength) return false;
    const derivedKey = await deriveScryptKey(secret, salt, keyLength, {
      N: n,
      r,
      p,
      maxmem: MAX_SCRYPT_MEMORY
    });
    return timingSafeEqual(derivedKey, expected);
  } catch {
    return false;
  }
}
